# TensorFlow Basics

In [1]:
import tensorflow as tf

In [2]:
# Make sure you are using 1.3 for exact sytnax matching!
print(tf.__version__)

1.12.0


## Tensors

In [3]:
hello = tf.constant('Hello')

In [4]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [5]:
world = tf.constant('World')

In [6]:
result = hello + world

In [7]:
result

<tf.Tensor 'add:0' shape=() dtype=string>

In [8]:
result

<tf.Tensor 'add:0' shape=() dtype=string>

In [9]:
type(result)

tensorflow.python.framework.ops.Tensor

In [10]:
hello

<tf.Tensor 'Const:0' shape=() dtype=string>

In [11]:
world

<tf.Tensor 'Const_1:0' shape=() dtype=string>

In [12]:
with tf.Session() as sess:
    result = sess.run(hello+world) ## add_1:0

In [13]:
result

b'HelloWorld'

In [14]:
type(result)

bytes

**Computations**

In [15]:
tensor_1 = tf.constant(1)
tensor_2 = tf.constant(2)

In [16]:
type(tensor_1)

tensorflow.python.framework.ops.Tensor

In [17]:
tensor_1 + tensor_2

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [18]:
sess

In [19]:
sess.close()

In [20]:
sess

In [21]:
tensor_1 + tensor_2

<tf.Tensor 'add_3:0' shape=() dtype=int32>

In [22]:
tensor_1 + tensor_2

<tf.Tensor 'add_4:0' shape=() dtype=int32>

In [23]:
result= tensor_1 + tensor_2 ## add_5:0

In [24]:
with tf.Session() as sess:
    print(sess.run(result)) 
    

3


In [25]:
type(result)

tensorflow.python.framework.ops.Tensor

In [26]:
with tf.Session() as sess:
    print(sess.run(tensor_1+tensor_2)) ## add_6:0


3


In [27]:
tensor_1+tensor_2 ## add_7:0

<tf.Tensor 'add_7:0' shape=() dtype=int32>

In [28]:
result+tensor_1 ## add_8:0 

<tf.Tensor 'add_8:0' shape=() dtype=int32>

## Operations

In [29]:
const = tf.constant(10)

In [30]:
fill_mat = tf.fill((4,4),10)

In [31]:
fill_mat

<tf.Tensor 'Fill:0' shape=(4, 4) dtype=int32>

In [32]:
type(fill_mat)

tensorflow.python.framework.ops.Tensor

In [33]:
myzeros = tf.zeros((4,4))

In [34]:
myones = tf.ones((4,4))

In [35]:
myrandn = tf.random_normal((4,4),mean=0,stddev=0.5)

In [36]:
myrandu = tf.random_uniform((4,4),minval=0,maxval=1)

In [37]:
my_ops = [const,fill_mat,myzeros,myones,myrandn,myrandu]

In [38]:
## Constant meaning
with tf.Session() as sess:
    hello = sess.run(hello + world)
    

In [39]:
hello

b'HelloWorld'

In [42]:
hello = tf.constant("hello1 ")
hello = hello + world
with tf.Session() as sess:
    print(sess.run(hello))

b'hello1 World'


## Interactive Session

Useful only for Notebook Sessions

In [43]:
# Only run this cell once!
sess = tf.InteractiveSession()

In [44]:
for op in my_ops:
    print(op.eval()) ## we're explicitly printig the result
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[-0.45000026 -0.03299951 -0.73531765  0.27951682]
 [-0.00546453  0.23786646  0.06446895  0.41740742]
 [ 0.3837333  -0.45969674  0.4637755  -0.52490765]
 [-1.0926499  -0.21222024  0.40936482 -0.90108883]]


[[0.19034433 0.55980253 0.39126635 0.4168172 ]
 [0.0433048  0.6223283  0.26007307 0.8491694 ]
 [0.19996428 0.23245478 0.40382457 0.49042833]
 [0.5562844  0.9738318  0.19561458 0.19992173]]




## Matrix Multiplication

In [45]:
a = tf.constant([ [1,2],
                  [3,4] ])

In [46]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [47]:
a.shape

TensorShape([Dimension(2), Dimension(2)])

In [48]:
b = tf.constant([[10],[100]])

In [49]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [50]:
result = tf.matmul(a,b)

In [ ]:
result.eval()