# TensorFlow Basics

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
print(tf.__version__)

1.12.0


## Tensors

### Constants


In [3]:
hello = tf.constant('Hello')

In [4]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [5]:
hello


<tf.Tensor 'Const:0' shape=() dtype=string>

In [6]:
world = tf.constant('World') ## Const_1:0

In [7]:
result = hello + world
## kind of operator overloading of '+' as tf.add()

In [8]:
print(result)

Tensor("add:0", shape=(), dtype=string)


In [9]:
type(result)

tensorflow.python.framework.ops.Tensor

In [10]:
with tf.Session() as sess:
    res_ = sess.run(hello+world) ## add_1:0

In [11]:
res_

b'HelloWorld'

In [12]:
type(res_)

bytes

In [13]:
# Constant doesnt mean it cant be reassigned "eg : a+="
with tf.Session() as sess:
    hello = sess.run(hello + world)
print(hello)

hello = tf.constant("hello1 ") ## const_2:
hello = hello + world
with tf.Session() as sess:
    print(sess.run(hello))

b'HelloWorld'
b'hello1 World'


**Computations**

In [14]:
tensor_1 = tf.constant(1)
tensor_2 = tf.constant(2)

In [15]:
type(tensor_1)

tensorflow.python.framework.ops.Tensor

In [16]:
tensor_1  # keeping track of all the initialized constant objects Cosnt_3:0 in comptn graph

<tf.Tensor 'Const_3:0' shape=() dtype=int32>

In [17]:
tensor_1 + tensor_2  

<tf.Tensor 'add_4:0' shape=() dtype=int32>

In [18]:
tensor_1 + tensor_2

<tf.Tensor 'add_5:0' shape=() dtype=int32>

In [19]:
tensor_1 + tensor_2

<tf.Tensor 'add_6:0' shape=() dtype=int32>

In [20]:
result= tensor_1 + tensor_2 ## add_7:0

In [21]:
with tf.Session() as sess:
    print(sess.run(result)) 
    

3


In [22]:
type(result)

tensorflow.python.framework.ops.Tensor

In [23]:
with tf.Session() as sess:
    print(sess.run(tensor_1+tensor_2)) ## add_8:0


3


In [24]:
tensor_1+tensor_2 ## add_9:0

<tf.Tensor 'add_9:0' shape=() dtype=int32>

In [25]:
result+tensor_1 ## add_10:0 

<tf.Tensor 'add_10:0' shape=() dtype=int32>

**Session**

In [26]:
sess

In [27]:
sess.close()

In [28]:
sess

## Operations

In [29]:
const = tf.constant(10)

In [30]:
fill_mat = tf.fill((4,4),10)

In [31]:
fill_mat

<tf.Tensor 'Fill:0' shape=(4, 4) dtype=int32>

In [32]:
type(fill_mat)

tensorflow.python.framework.ops.Tensor

In [33]:
myzeros = tf.zeros((4,4))

In [34]:
myones = tf.ones((4,4))

In [35]:
myrandn = tf.random_normal((4,4),mean=0,stddev=0.5)

In [36]:
myrandu = tf.random_uniform((4,4),minval=0,maxval=1)

In [37]:
my_ops = [const,fill_mat,myzeros,myones,myrandn,myrandu]

**Numpy to Tensor to Numpy**

In [38]:
# Numpy array to tf.tensor
a=tf.constant(np.arange(1,10).reshape(3,3))
a

<tf.Tensor 'Const_6:0' shape=(3, 3) dtype=int64>

In [39]:
# tf.tensor to numpy array
# method 1 
with tf.Session() as sess:
    k_numpy = sess.run(a)

In [40]:
k_numpy # deep copy

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
k_numpy[0,0]= 10
print(k_numpy)
with tf.Session() as sess:
    print(sess.run(a))

# deep copy as change in one didnt reflect in the other.

[[10  2  3]
 [ 4  5  6]
 [ 7  8  9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### Indexing and Slicing

In [42]:
a=tf.constant(np.arange(1,10).reshape(3,3))

In [43]:
a[2]

<tf.Tensor 'strided_slice:0' shape=(3,) dtype=int64>

In [44]:
a[2]

<tf.Tensor 'strided_slice_1:0' shape=(3,) dtype=int64>

In [45]:
with tf.Session() as sess:
    print(sess.run(a[1]))

[4 5 6]


In [46]:
a[1:3,2]

<tf.Tensor 'strided_slice_3:0' shape=(2,) dtype=int64>

In [47]:
with tf.Session() as sess:
    print(sess.run(a[1:3,2]))

[6 9]


In [48]:
print(a.shape)


(3, 3)


## Interactive Session

Useful only for Notebook Sessions

In [49]:
# Only run this cell once!
sess = tf.InteractiveSession()

In [50]:
for op in my_ops:
    ## op.eval() here works same as sess.run(op)
    print(op.eval()) ## we're explicitly printig the result
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[-0.24853504 -0.69762856  0.50741184 -0.5231508 ]
 [-0.17865609 -0.12436188 -0.60335463  0.32622793]
 [ 0.17033152 -0.2601391   0.72647667 -0.4932019 ]
 [-0.04729211 -0.13552217 -0.19374755  0.09748516]]


[[0.7553537  0.68379426 0.3038379  0.6777468 ]
 [0.32030153 0.6856313  0.64696157 0.96980476]
 [0.51004434 0.54851246 0.24017453 0.65765214]
 [0.9773848  0.7436478  0.94662046 0.07855654]]




## Matrix Multiplication

In [51]:
a = tf.constant([ [1,2],
                  [3,4] ])

In [52]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [53]:
a.shape

TensorShape([Dimension(2), Dimension(2)])

In [54]:
b = tf.constant([[10],[100]])

In [55]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [56]:
result = tf.matmul(a,b)

In [57]:
result.eval()

array([[210],
       [430]], dtype=int32)

In [58]:
# tf.assign wont work on constant but variables. This how a varible's value is chaged.
tf.assign(b,[2])

AttributeError: 'Tensor' object has no attribute 'assign'

In [59]:
# wont work on these either
tf.assign(result,[2])

AttributeError: 'Tensor' object has no attribute 'assign'

In [60]:
print(result)
# type -> tensor 
# operation by which created -> "MatMul"


Tensor("MatMul:0", shape=(2, 1), dtype=int32)
